<?php
require "./connection.php";
// require "./mysqli_get_client_info()_and_mysqli_get_client_version()_and_mysqli_get_host_info()_and_host_info_and_mysqli_get_proto_info()_and_protocol_version_and_mysqli_get_server_info()_and_server_info_and_mysqli_get_server_version()_and_server_version/information.php";
// echo "<br /><br />";
// require "./mysqli_query()_and_query()/index.php";
// echo "<br /><br />";
// require "./fetch_transactions/index.php";
// echo "<br /><br />";
// require "./join_transactions/index.php";
// echo "<br /><br />";
// require "./math_transactions/index.php";
// echo "<br /><br />";
// require "./mysqli_affected_rows()_and_affected_rows/index.php";
// echo "<br /><br />";
// require "./prepare()_and_bind_param()_and_execute()_and_bind_result()_and_fetch()/index.php";
// echo "<br /><br />";
// require "./mysqli_autocommit()_and_autocommit()_and_mysqli_commit()_and_commit()_and_mysqli_rollback()_and_rollback()/index.php";
// echo "<br /><br />";
require "./mysqli_real_escape_string()_and_real_escape_string()/index.php";
echo "<br /><br />";
